services:
  - type: web
    name: hedera-token-analyzer-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This means it will be set manually in the dashboard
      - key: MIRROR_NODE_URL
        value: https://mainnet-public.mirrornode.hedera.com/api/v1
      - key: MIRROR_NODE_TIMEOUT
        value: 30000
      - key: MAX_RETRIES
        value: 3
      - key: ALLOWED_ORIGINS
        value: https://hedera-token-analyzer.netlify.app
      - key: RATE_LIMIT
        value: 150
      - key: BATCH_SIZE
        value: 50
      - key: HOLDER_BATCH_SIZE
        value: 25
      - key: PROCESSING_DELAY
        value: 200
    disk:
      name: token-data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true
